[package]
name = "you/better-icon-picker"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
React = "jsdotlua/react@17.0.0"
ReactRoblox = "jsdotlua/react-roblox@17.0.0"
